version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5173:3000"
    volumes:
      - ./src:/usr/src/app/src
      - ./public:/usr/src/app/public
    command: ["yarn", "dev"]
