version: "3.8"

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: chat
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8080:80"
    depends_on:
      - db

  backend:
    build: ./backend
    environment:
      DATABASE_URL: postgres://user:password@db:5432/chat
      PORT: 5001
    ports:
      - "5001:5001"
    depends_on:
      - db
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules # Para evitar problemas de permissão

  frontend:
    build: ./frontend
    environment:
      VITE_API_URL: http://140.238.191.187:5001
      VITE_CHAT_SERVICE_URL: http://140.238.191.187:11434
    ports:
      - "5173:5173"
    depends_on:
      - backend
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules # Para evitar problemas de permissão

volumes:
  db-data:
