# Start with Ubuntu base image
FROM ubuntu:latest

# Install necessary packages
RUN apt-get update && apt-get install -y \
    python3 \
    python3-pip \
    python3-venv \
    curl \
    && rm -rf /var/lib/apt/lists/*


# Set up a virtual environment
ENV VIRTUAL_ENV=/opt/venv
RUN python3 -m venv $VIRTUAL_ENV
ENV PATH="$VIRTUAL_ENV/bin:$PATH"

# Set working directory
WORKDIR /api

# Copy requirements file and install dependencies
COPY requirements.txt .
RUN pip install -r requirements.txt

# Copy all files from the local directory to the container
COPY . /api/

# Expose FastAPI port
EXPOSE 8000

# Create a startup script
RUN echo '#!/bin/bash\n\
    uvicorn main:app --host 0.0.0.0 --port 8000' > /api/start.sh && \
    chmod +x /api/start.sh


CMD ["/api/start.sh"]
