version: "3.3"

services:
  ollama:
    image: ollama/ollama
    volumes:
      - ollama:/root/.ollama
    ports:
      - "11434:11434"

  fastapi:
    build: .
    ports:
      - "8000:8000"
    environment:
      - MODEL_URL=http://ollama:11434/api/generate
    depends_on:
      - ollama

volumes:
  ollama:
